### ISSUE TITLE
Possible filename error

### ISSUE THREAD

**Issue by hannahgooding** [oliverjam/node-file-server#2]
Section: Cross-Platform Paths

> ...then run `node index.js`. You should see an error logged, because there is no "workshop" directory inside of workshop/...

Is this meant to be `node practice.js`?

**Comment by oliverjam** [comment]
Oh this was from before I added `nodemon`, sorry 😬 

If you've already run `npm run practice` it should have automatically restarted anyway. I'll remove that bit
